name: Release build

on:
  workflow_dispatch

jobs:
  build:
    name: Release build
    strategy:
      matrix:
        include:
          - platform: 1
            platform_name: ios
    
    runs-on: macos-latest
    steps:
      - name: Build for ${{ matrix.platform_name }}
        env:
          password: ${{ secrets.ELLIE_MINI_SECRET }}
        run: |
          export PATH=/opt/procursus/bin:/opt/homebrew/bin:$PATH
          export RUNNER=1
          gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}
          # Additionally build TrollStore (auto JIT) tipa for iOS
          if [ "${{ matrix.platform_name }}" == "ios" ]; then
            gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }} TROLLSTORE_JIT_ENT=1
          fi

      - name: Upload regular ipa
        uses: actions/upload-artifact@v3
        with:
          name: net.kdt.pojavlauncher-${{ matrix.platform_name }}.ipa
          path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}.ipa

      - name: Upload regular tipa
        uses: actions/upload-artifact@v3
        with:
          name: net.kdt.pojavlauncher-${{ matrix.platform_name }}.tipa
          path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}-trollstore.tipa

      - name: Upload PojavLauncher.dSYM
        uses: actions/upload-artifact@v3
        with:
          name: PojavLauncher.dSYM
          path: artifacts/PojavLauncher.dSYM
