name: Release build

on:
  workflow_dispatch

jobs:
  build:
    name: Release build
    runs-on: macos-latest
    steps:
      - name: Build for ios
        run: |
          export PATH=/opt/homebrew/bin:$PATH
          export RUNNER=1
          make package PLATFORM=ios
      - name: Upload regular ipa
        uses: actions/upload-artifact@v3
        with:
          name: app.ipa
          path: artifacts/app.ipa

      - name: Upload regular tipa
        uses: actions/upload-artifact@v3
        with:
          name: app.tipa
          path: artifacts/app.tipa
